# Generated by Django 6.0 on 2025-12-25 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Carrera')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción de la Carrera')),
            ],
            options={
                'verbose_name': 'Carrera Universitaria',
                'verbose_name_plural': 'Carreras Universitarias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Recurso')),
                ('descripcion', models.TextField(verbose_name='Descripción Detallada')),
                ('url_externa', models.URLField(max_length=500, verbose_name='URL Externa')),
                ('tipo', models.CharField(choices=[('app', 'Aplicación'), ('herramienta', 'Herramienta Web'), ('pagina_web', 'Página Web'), ('ia', 'Inteligencia Artificial'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de Recurso')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='recursos.carrera', verbose_name='Carrera Asociada')),
            ],
            options={
                'verbose_name': 'Recurso Digital',
                'verbose_name_plural': 'Recursos Digitales',
                'ordering': ['nombre'],
                'unique_together': {('nombre', 'carrera')},
            },
        ),
    ]
