# Generated by Django 6.0 on 2025-12-27 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recursos.carrera', verbose_name='Carrera del Estudiante'),
        ),
    ]
