# Generated by Django 6.0 on 2026-01-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0003_perfil_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='Estado de Aprobación'),
        ),
    ]
