# Generated by Django 6.0 on 2026-01-04 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0005_recurso_sugerido_por'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recurso',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recurso',
            name='carreras',
            field=models.ManyToManyField(blank=True, related_name='recursos', to='recursos.carrera', verbose_name='Carreras Asociadas'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='nombre',
            field=models.CharField(max_length=200, unique=True, verbose_name='Nombre del Recurso'),
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='carrera',
        ),
    ]
