# Generated by Django 6.0 on 2026-01-04 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0006_alter_recurso_unique_together_recurso_carreras_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recursos_imagenes/', verbose_name='Imagen Representativa'),
        ),
    ]
