# Generated by Django 6.0 on 2026-01-17 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0007_recurso_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='carreras_imagenes/', verbose_name='Imagen de la Carrera'),
        ),
    ]
