# Generated by Django 6.0 on 2026-01-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0009_valoracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='uso_ideal',
            field=models.TextField(blank=True, help_text='Liste los usos ideales del recurso, uno por línea.', null=True, verbose_name='Uso Ideal'),
        ),
    ]
