# Generated by Django 6.0 on 2026-01-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0010_recurso_uso_ideal'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='recursos_favoritos',
            field=models.ManyToManyField(blank=True, related_name='favorito_de', to='recursos.recurso', verbose_name='Recursos Favoritos'),
        ),
    ]
