# Generated by Django 6.0 on 2026-01-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0011_perfil_recursos_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='puntos',
            field=models.IntegerField(default=0, verbose_name='Puntos de Gamificación'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='racha_actual',
            field=models.IntegerField(default=0, verbose_name='Racha de Conexión'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ultima_conexion_racha',
            field=models.DateField(blank=True, null=True, verbose_name='Última Conexión para Racha'),
        ),
    ]
