# Generated by Django 6.0 on 2026-01-30 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0012_perfil_puntos_perfil_racha_actual_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('login_diario', 'Login Diario'), ('valorar_recurso', 'Valorar un Recurso'), ('sugerir_recurso', 'Sugerir un Recurso'), ('visitar_recurso', 'Visitar un Recurso')], max_length=50, unique=True, verbose_name='Clave de Misión')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Misión')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('puntos_recompensa', models.IntegerField(default=10, verbose_name='Puntos de Recompensa')),
                ('activa', models.BooleanField(default=True, verbose_name='Misión Activa')),
            ],
            options={
                'verbose_name': 'Misión',
                'verbose_name_plural': 'Misiones',
            },
        ),
        migrations.CreateModel(
            name='MisionDiariaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Asignación')),
                ('completada', models.BooleanField(default=False, verbose_name='Completada')),
                ('fecha_completado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Completado')),
                ('mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_diarias', to='recursos.mision')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misiones_diarias', to='recursos.perfil')),
            ],
            options={
                'verbose_name': 'Misión Diaria de Usuario',
                'verbose_name_plural': 'Misiones Diarias de Usuarios',
                'unique_together': {('perfil', 'mision', 'fecha_asignacion')},
            },
        ),
    ]
