# Generated by Django 6.0 on 2026-01-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0013_mision_misiondiariausuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='ultima_conexion_racha',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última Conexión para Racha'),
        ),
    ]
