# Generated by Django 6.0 on 2026-02-01 02:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0014_alter_perfil_ultima_conexion_racha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='misiondiariausuario',
            name='fecha_asignacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de Asignación'),
        ),
    ]
