# Generated by Django 6.0 on 2026-02-01 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0015_alter_misiondiariausuario_fecha_asignacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialVisitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Visita')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_visitas', to='recursos.perfil')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='recursos.recurso')),
            ],
            options={
                'verbose_name': 'Historial de Visita',
                'verbose_name_plural': 'Historiales de Visitas',
                'ordering': ['-fecha_visita'],
            },
        ),
    ]
